apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
  labels:
    app: django-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-deploy
  template:
    metadata:
      labels:
        app: django-deploy
    spec:
      containers:
      - image: jisunpark/django-sample:30
        name: django-app
        ports:
        - containerPort: 8000