apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deploy
  labels:
    app: golang-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-deploy
  template:
    metadata:
      labels:
        app: golang-deploy
    spec:
      containers:
      - image: jisunpark/golang-sample:16
        name: golang-app
        ports:
        - containerPort: 8000